### ISSUE TITLE
How to configure? Chat id?

### ISSUE THREAD

**Issue by SuperJMN** [oxozle/serilog-sinks-telegram#1]
I've created my bot with Bot Father and I got a token, but it seems I also need a chat Id. How do I get it?

Also, this URL is failing:
https://api.telegram.org/botTOKEN/getUpdates

**Comment by oxozle** [comment]
To get your id navigate to https://api.telegram.org/botTOKEN/getUpdates

**Comment by oxozle** [comment]
You need to insert TOKEN in url, like To get your id navigate to https://api.telegram.org/botXXXXXXXXXXXXXXXXXXX/getUpdates

**Comment by SuperJMN** [comment]
Thanks! I'm a bit blind... sorry!

**Comment by SuperJMN** [comment]
I've filled the url with my token and all I receive is this:

{"ok":true,"result":[]}

where is the id? :)

**EDIT:** OK, found it. In order to see something, **you have to start a chat with the bot** and then, the JSON that this GET method returns has a part with chat : { "id": "some number" } }... where the chat id is "some number".

**Comment by oxozle** [comment]
Oh, no problem. You should add your bot to your contacts list. Print `/start`. This will add you as contacts to your bot. Then print some message like `test`. After that open url with `getUpdates`.
